sudo: false
language: python
cache: pip
python:
  - "2.7"
before_install:
  - python --version
  - uname -a
  - ls -a
  - which pip
  - "pip install --upgrade pip"
install:
  - "echo time to install stuff"
  - "pip install git+https://github.com/scipy/scipy.git"
script:
  - "cd handwriting-recognition"
  - "python run.py"
notifications:
  emails: false
